// <auto-generated />
namespace Pomodoro.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class secondadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202101301950547_second add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
